---
development:
  DATA_ID1: 'O-A0003-001'
  DATA_ID2: 'O-A0002-001'
  AUTH_KEY: 'CWB-404A6D6C-E6C4-465D-8BB7-C2435169D3E2'
  FORMAT: 'xml'
  TOKEN: 'YxZhGGgNtUyzW7oi6EPpKQ'
test:
  DATA_ID1: 'O-A0003-001'
  DATA_ID2: 'O-A0002-001'
  AUTH_KEY: 'CWB-404A6D6C-E6C4-465D-8BB7-C2435169D3E2'
  FORMAT: 'xml'
  TOKEN: 'YxZhGGgNtUyzW7oi6EPpKQ'
